- hosts: all
  roles:

          - role: k8s_master
            when: inventory_hostname in groups['tag_name_k8s_master']
          - role: k8s_worker
            when: inventory_hostname in groups['tag_name_k8s_worker']
          - role: join_cluster
